version: '3.3'

services:
  web:
    build:
      context: .
      dockerfile: docker/Dockerfile
    env_file: .env
    volumes:
      - .:/var/www
    ports:
      - 8080:80
    entrypoint: /opt/entrypoint.sh

  postgres:
    image: postgres
    env_file: .env