version: '3.3'

services:
  web:
    build:
      context: .
      dockerfile: docker/Dockerfile
    env_file: .env
    volumes:
      - .:/var/www
      - ./docker/config/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8020:80
    entrypoint: /opt/entrypoint.sh

  db:
    image: mysql
    env_file: .env
    volumes:
      - ./docker/config/mysql/custom.cnf:/etc/mysql/conf.d/custom.cnf