<?php
namespace app\modules\admin;

use yii\base\Module;

/**
 * Class AdminModule
 * @package app\modules\admin
 */
class AdminModule extends Module
{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }
}